DROP MATERIALIZED VIEW IF EXISTS album_financiero.ds_presupuesto_aplicado;
DROP MATERIALIZED VIEW IF EXISTS album_financiero.ds_viaje_id;
DROP MATERIALIZED VIEW IF EXISTS album_financiero.dim_viajes_grupo;
DROP MATERIALIZED VIEW IF EXISTS album_financiero.ds_viaje_tipo_cambio;
DROP MATERIALIZED VIEW IF EXISTS album_financiero.dim_tipo_inversion;
DROP MATERIALIZED VIEW IF EXISTS album_financiero.ds_inversiones_movimientos;
DROP MATERIALIZED VIEW IF EXISTS album_financiero.dim_razon_uso;
DROP MATERIALIZED VIEW IF EXISTS album_financiero.ds_creditos_periodo;
DROP MATERIALIZED VIEW IF EXISTS album_financiero.ds_deuda_id;
DROP MATERIALIZED VIEW IF EXISTS album_financiero.dim_metodo_pago_general;
DROP MATERIALIZED VIEW IF EXISTS album_financiero.ds_presupuesto_mensual_especifico;
DROP MATERIALIZED VIEW IF EXISTS album_financiero.dim_categoria_movimiento;
DROP MATERIALIZED VIEW IF EXISTS album_financiero.ds_presupuesto_mensual_regular_dinero;
DROP MATERIALIZED VIEW IF EXISTS album_financiero.dim_tipo_credito;
DROP MATERIALIZED VIEW IF EXISTS album_financiero.help_presupuesto_especifico;
DROP MATERIALIZED VIEW IF EXISTS album_financiero.dim_deuda_nombre;
DROP MATERIALIZED VIEW IF EXISTS album_financiero.dim_nombre;
DROP MATERIALIZED VIEW IF EXISTS album_financiero.ds_nombre;
DROP MATERIALIZED VIEW IF EXISTS album_financiero.ds_ingresos;
DROP MATERIALIZED VIEW IF EXISTS album_financiero.dim_ingresos;
DROP MATERIALIZED VIEW IF EXISTS album_financiero.ds_inversiones_impacto;


REFRESH MATERIALIZED VIEW album_financiero.dim_tipo_inversion;
REFRESH MATERIALIZED VIEW album_financiero.dim_metodo_pago_general;
REFRESH MATERIALIZED VIEW album_financiero.dim_nombre;
REFRESH MATERIALIZED VIEW album_financiero.dim_tipo_credito;
REFRESH MATERIALIZED VIEW album_financiero.dim_categoria_movimiento;
REFRESH MATERIALIZED VIEW album_financiero.dim_viajes_grupo;
REFRESH MATERIALIZED VIEW album_financiero.dim_razon_uso;
REFRESH MATERIALIZED VIEW album_financiero.dim_deuda_nombre;
REFRESH MATERIALIZED VIEW album_financiero.dim_ingresos;
REFRESH MATERIALIZED VIEW album_financiero.ds_creditos_periodo;
REFRESH MATERIALIZED VIEW album_financiero.ds_nombre;
REFRESH MATERIALIZED VIEW album_financiero.ds_deuda_id;
REFRESH MATERIALIZED VIEW album_financiero.ds_inversiones_movimientos;
REFRESH MATERIALIZED VIEW album_financiero.ds_viaje_id;
REFRESH MATERIALIZED VIEW album_financiero.ds_viaje_tipo_cambio;
REFRESH MATERIALIZED VIEW album_financiero.ds_presupuesto_mensual_especifico;
REFRESH MATERIALIZED VIEW album_financiero.ds_presupuesto_mensual_regular_dinero;
REFRESH MATERIALIZED VIEW album_financiero.ds_presupuesto_aplicado;
REFRESH MATERIALIZED VIEW album_financiero.ds_ingresos;
REFRESH MATERIALIZED VIEW album_financiero.ds_inversiones_impacto;

REFRESH MATERIALIZED VIEW album_financiero.v_ds_creditos_periodo;
REFRESH MATERIALIZED VIEW album_financiero.v_ds_nombre;
REFRESH MATERIALIZED VIEW album_financiero.v_ds_deuda_id;
REFRESH MATERIALIZED VIEW album_financiero.v_ds_inversiones_movimientos;
REFRESH MATERIALIZED VIEW album_financiero.v_ds_viaje_id;
REFRESH MATERIALIZED VIEW album_financiero.v_ds_viaje_tipo_cambio;
REFRESH MATERIALIZED VIEW album_financiero.v_ds_presupuesto_mensual_especifico;
REFRESH MATERIALIZED VIEW album_financiero.v_ds_presupuesto_mensual_regular_dinero;
REFRESH MATERIALIZED VIEW album_financiero.v_ds_presupuesto_aplicado;
REFRESH MATERIALIZED VIEW album_financiero.v_ds_ingresos;
REFRESH MATERIALIZED VIEW album_financiero.v_ds_inversiones_impacto;
REFRESH MATERIALIZED VIEW album_financiero.help_presupuesto_especifico;